# Generated by Django 4.1.6 on 2023-02-16 05:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_attachments_attachments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachments',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 16, 11, 4, 21, 863451)),
        ),
        migrations.AlterField(
            model_name='attachments',
            name='attachment',
            field=models.FileField(null=True, upload_to='uploads/attachments/'),
        ),
        migrations.AlterField(
            model_name='chats',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 16, 11, 4, 21, 863451)),
        ),
        migrations.AlterModelTable(
            name='attachments',
            table='attachments',
        ),
        migrations.AlterModelTable(
            name='chats',
            table='chats',
        ),
    ]
